[[main]]
  name = "Home"
  url = ""
  weight = -110

# Submenus are done this way: parent -> identifier
[[main]]
  name = "Java Learning Series"
  identifier = "java_learning_series"
  weight = -105
[[main]]
  parent = "java_learning_series"
  name = "Exploring Java 8"
  url = "exploringjava8/"

[[main]]
  name = "About"
  url = "about/"
  weight = -104

# social menu links
[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/anilsablepatil"
[[social]]
  name = "linkedin"
  weight = 2
  url = "https://www.linkedin.com/in/anil-sable-30947389/"
[[social]]
  name = "facebook"
  weight = 3
  url = "https://www.facebook.com/AnilSablePatil"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"